apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: java
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - name: test
        image: tpavan997/myapp:latest
        ports:
        - containerPort: 8080
